### PR TITLE
Added the read-history and write-history functions.

### PR DESCRIPTION
**Pull request by marvinkohl**
I added the functions already requested in issue #6.

### CODE REVIEW

**Comment by vindarel** [comment]
That's a welcome addition, thank you. 

Didn't you end up making the up and down keys do what's expected ?

**Comment by marvinkohl** [comment]
What do you mean?
The keys are doing what I expecting.

**Comment by vindarel** [comment]
I built an executable with this new feature, I used write-history to write the commands used to a given file, and when I quit it and run it again, the up arrow doesn't automagically read the history file and display the last used command. In other words, when the app starts over, the up arrow doesn't have anything to show (and that seems logical at this point).

However, during a readline "session" it worked (up, down, C-r) (it was already working).

What use case does this PR exactly fix for you ?

**Comment by marvinkohl** [comment]
It doesn't automatically read the history file. You have to call `read-history` before `readline`.

**Comment by vindarel** [comment]
Oh, makes sense :)

**Pull request merged**
